config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  get 'pages/itinerary'

  get 'pages/documents'

  get 'pages/requests'

  get 'pages/disclaimer'

  get 'pages/about'

  get 'pages/aboutus'

  get 'pages/timetravel'

  get 'pages/destination'

  get 'pages/jfk'

  get 'pages/store'

  devise_for :users
  get 'welcome/index'

  root 'welcome#index'

end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def itinerary
  end

  def documents
  end

  def requests
  end

  def disclaimer
  end

  def about
  end

  def jfk
  end
  
  def store
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: [:show, :edit, :update, :destroy]

  # GET /purchases
  # GET /purchases.json
  def index
    @purchases = Purchase.all
  end

  # GET /purchases/1
  # GET /purchases/1.json
  def show
  end

  # GET /purchases/new
  def new
    @purchase = Purchase.new
  end

  # GET /purchases/1/edit
  def edit
  end

  # POST /purchases
  # POST /purchases.json
  def create
    @purchase = Purchase.new(purchase_params)

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to @purchase, notice: 'Purchase was successfully created.' }
        format.json { render :show, status: :created, location: @purchase }
      else
        format.html { render :new }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchases/1
  # PATCH/PUT /purchases/1.json
  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to @purchase, notice: 'Purchase was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy
    @purchase.destroy
    respond_to do |format|
      format.html { redirect_to purchases_url, notice: 'Purchase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_params
      params.require(:purchase).permit(:fname, :lname, :dob, :ssn, :address, :line2, :city, :state, :zip, :creditcard, :cardtype, :requests)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

<head>
  <title>Black Magic: Time travelers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
      <script src="/assets/jquery.min.js"></script>
    <script src="/assets/jquery.dropotron.min.js"></script>
    <script src="/assets/skel.min.js"></script>
    <script src="/assets/skel-layers.min.js"></script>
    <script src="/assets/init.js"></script>
    <link rel="shortcut icon" href="/assets/logo.jpg" /> 
</head>

		<!-- Header -->
			<div id="header-wrapper" class="wrapper">
				<div id="header">
					
					<!-- Logo -->
						<div id="logo">
							<h1><a href="index.html">Black Magic</a></h1>
							<p>Inovators in Time Travel Technologies since 2015</p>
						</div>
					
					<!-- Nav -->
						<nav id="nav">
							<ul>
								<li><%= link_to "HOME", root_path%></li>
								<li class= "current">
									<a href="">Travel Reservations</a>
									<ul>
										<li><%= link_to "Purchase Ticket", new_purchase_path%></li>
										<li><%= link_to "Rool Call", purchases_path%></li>
										<li><%= link_to "Itinerary", pages_itinerary_path%></li>
										<li>
											<a href="">Your Trip</a>
											<ul>
												<li><%= link_to "Edit User Info", edit_user_registration_path%></li>
												<li><%= link_to "Travel Ticket", purchases_path%></li>
												<li><%= link_to "Travel Documents", pages_documents_path%></li>
												<li><%= link_to "Disclaimer", pages_disclaimer_path%></li>
											</ul>
										</li>
										<li><%= link_to "JFK Assassination History", pages_jfk_path%></li>
									</ul>
								</li>
								<li><%= link_to "ONLINE STORE", pages_store_path%></li>
								<li><%= link_to "ABOUT", pages_about_path%></li>
								<li><a href="#footer">Contact</a></li>
							</ul>
						</nav>

				</div>
			</div>

	<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<body class="homepage">
<%= yield %>
		<!-- Highlights -->
			<div class="wrapper style3">
				<div class="title">Our Other Trips Through Time</div>
				<div id="highlights" class="container">
					<div class="row 150%">
						<div class="4u">
							<section class="highlight">
								<a href="#" class="image featured"><img src="/assets/pic02.jpg" alt="" /></a>
								<h3><a href="#">The Apollo Moon Landing</a></h3>
								<p>In this Journey back to the time of the Cold War, adventerures will enjoy the unique pleasure of watching Niel Armstrong take Man's "Ginat Leap"</p>
								<ul class="actions">
									<li><a href="#" class="button style1">Learn More</a></li>
								</ul>
							</section>
						</div>
						<div class="4u">
							<section class="highlight">
								<a href="#" class="image featured"><img src="/assets/pic03.jpg" alt="" /></a>
								<h3><a href="#">Boston Tea Party</a></h3>
								<p>Come Join Us on our brief gettaway to a time when the American Citizens protested the English Tea Tax and started a Revolution for Independence.</p>
								<ul class="actions">
									<li><a href="#" class="button style1">Learn More</a></li>
								</ul>
							</section>
						</div>
						<div class="4u">
							<section class="highlight">
								<a href="#" class="image featured"><img src="/assets/pic04.jpg" alt="" /></a>
								<h3><a href="#">Prohibition</a></h3>
								<p>welcome to the Roaring Twenties. This quick stroll down memory lane will have our travelers fully engulfed in a time when crime was the law of the land.</p>
								<ul class="actions">
									<li><a href="#" class="button style1">Learn More</a></li>
								</ul>
							</section>
						</div>
					</div>
				</div>
			</div>

		<!-- Footer -->
			<div id="footer-wrapper" class="wrapper">
				<div class="title">Get In Touch</div>
				<div id="footer" class="container">
					<header class="style1">
						<h2>Need To Conatact a Black Magic Rep?</h2>
						<p>
							By sending a message through the messaging service to your right you will reaching our Customer Service Agents Directly<br />
							Please double check the spelling of the email to insure a response.
						</p>
					</header>
					<hr />
					<div class="row 150%">
						<div class="6u">

							<!-- Contact Form -->
								<section>
									<form method="post" action="#">
										<div class="row 50%">
											<div class="6u">
												<input type="text" name="name" id="contact-name" placeholder="Name" />
											</div>
											<div class="6u">
												<input type="text" name="email" id="contact-email" placeholder="Email" />
											</div>
										</div>
										<div class="row 50%">
											<div class="12u">
												<textarea name="message" id="contact-message" placeholder="Message" rows="4"></textarea>
											</div>
										</div>
										<div class="row">
											<div class="12u">
												<ul class="actions">
													<li><input type="submit" class="style1" value="Send" /></li>
													<li><input type="reset" class="style2" value="Reset" /></li>
												</ul>
											</div>
										</div>
									</form>
								</section>

						</div>
						<div class="6u">
						
							<!-- Contact -->
								<section class="feature-list small">
									<div class="row">
										<div class="6u">
											<section>
												<h3 class="icon fa-home">Address</h3>
												<p>
													Black Magic<br />
													27 Richter St #987<br />
													Providence, RI 02879
												</p>
											</section>
										</div>
										<div class="6u">
											<section>
												<h3 class="icon fa-comment">Social</h3>
												<p>
													<a href="#">@Black Magic</a><br />
													<a href="#">linkedin.com/blackmagic</a><br />
													<a href="#">facebook.com/blackmagic</a>
												</p>
											</section>
										</div>
									</div>
									<div class="row">
										<div class="6u">
											<section>
												<h3 class="icon fa-envelope">Email</h3>
												<p>
													<a href="#">info@blackmagic.com</a>
												</p>
											</section>
										</div>
										<div class="6u">
											<section>
												<h3 class="icon fa-phone">Phone</h3>
												<p>
													(401) 450-8878
												</p>
											</section>
										</div>
									</div>
								</section>
								
						</div>
					</div>
					<hr />
				</div>
				<div id="copyright">
					<ul>
						<li>&copy; Black Magic Time Travel</li><li>Design: <a href="https://www.facebook.com/jstearnzy">jpStearns @Kind inc.</a></li>
					</ul>
				</div>
			</div>
</body>
</html>

app/views/pages/about.html.erb
		<!-- Main -->
			<div class="wrapper style2">
				<div class="title">|ABOUT US|</div>
				<div id="main" class="container">
					<div class="row 150%">
						<div class="8u">
						
							<!-- Content -->
								<div id="content">
									<article class="box post">
										<header class="style1">
											<h2>Here you can learn about Black Magic and the technologies that we have developed.</h2>
											<p>Where would you go if you could go anywhere in time?</p>
										</header>
										<a href="#" class="image featured">
											<img src="/assets/aboutpic.jpg" alt="" />
										</a>
										<h2>Our Foundations:</h2>
										<p>In 2015 Black Magic's founder JP Stearns discovered the Grand Unified Theory of Everything while attending the University of Rhode Island. It was this discovery that made our time travel getaways a possibility.</p>
										<p>It was through a relentless effort to unify the equations of Electro-Magnetism and and Quantum Gravity to Replicate the moment of the big bang, led JP to the center of black holes.  In the center of a black hole the space time continuum because one. There is no more space time, instead there is what is known as a singularity.  In 2013 JP lead a team of Pioneers through the center of Serius-B the Super Massive Black Hole at the Center of the Milky Way Galaxy. What they found was that through a series of very precise and advanced calculations that they could invert space time into time space and could begin to control the arrow of time spatially the way that time travels through our dimension.</p>
										<h2>Our Technology:</h2>
										<p>We here at Black Magic have consulted the world's finisest statisticians and philosophers to develop a moral framework for traveling into the past. We have developed a no foot-print philosophy and leave no trace as we travel into the past, by staying organized and adhereing to strict disciplines and developing individualized itineraries with qualified history experts that help us to go un noticed.</p>

										<h2>Our Mission:</h2>
										<p>They say that there is no better way to prepare for the future than to learn from the past, and we here at Black Magic embody this ideal. We believe that by giving the present generations answers to the biggest mysteries in history we can begin to truly define who we are as a speciels </p>
									</article>
									<div class="row 150%">
										<div class="6u">
											<section class="box">
												<header>
													<h2>Come Meet Our Team</h2>
												</header>
												<a href="#" class="image featured"><img src="/assets/mk.jpg" alt="" /></a>
												<p>Black Magic has recruited the top minds in the United States of America to contribute to the most extreme of Mankind's accomplishments.  We are able to ensure safety and accuracy as we travel through the past and future alike.</p>
												<a href="#" class="button style1">More</a>
											</section>
										</div>
										<div class="6u">
											<section class="box">
												<header>
													<h2>Tour Our High-Tech Labs</h2>
												</header>
												<a href="#" class="image featured"><img src="/assets/dragon.jpg" alt="" /></a>
												<p>Our State-Of-The-Art facilities are now open to the public for tours. Please contact one of our customer service representaitves to book a tour today and get an upclose look at your vessel to time control. We're excited to see you soon</p>
												<a href="#" class="button style1">More</a>
											</section>
										</div>
									</div>
								</div>
						
						</div>
						<div class="4u">
							
							<!-- Sidebar -->
								<div id="sidebar">
									<section class="box">
										<header>
											<h2>We will be traveling through Serius the black hole</h2>
										</header>
										<p>At the center of the Milkyway Galaxy lies an invisible monster. A Super Masive Black Hole more than 30 million million degrees in Farenheight. Thanks to our dedicated physicists Black Magic is proud to announce that we can now safely take you through the space time continuum to any point in history.</p>
										<a href="#" class="button style1">Learn More</a>
									</section>
									<section class="box">
										<header>
											<h2>Those Who Made It Possible</h2>
										</header>
										<ul class="style2">
											<li>
												<article class="box post-excerpt">
													<a href="#" class="image left"><img src="/assets/pic08.jpg" alt="" /></a>
													<h3><a href="#">Professor Stephen Hawking</a></h3>
													<p>Though he is handicapped by Lue Gerhig's disease Professor Hawking's relentless dedication to the science of black holes has paved the way to endless possibilities.</p>
												</article>
											</li>
											<li>
												<article class="box post-excerpt">
													<a href="#" class="image left"><img src="/assets/pic09.jpg" alt="" /></a>
													<h3><a href="#">Albert Einstein</a></h3>
													<p>Through his application of General Relativity Albert Einstein developed the theory that predicted black holes and lead to our understanding of the Swartzchild Radius.</p>
												</article>
											</li>
											<li>
												<article class="box post-excerpt">
													<a href="#" class="image left"><img src="/assets/pic10.jpg" alt="" /></a>
													<h3><a href="#">Sir Issac Newton</a></h3>
													<p>In his mid twenties Issac Newton proved the existence of the force of gravity and developed the language of Calculus to explain his theories. We owe our technologies to this ground breaking genius.</p>
												</article>
											</li>
										</ul>
										<a href="#" class="button style1">Archives</a>
									</section>

								</div>
							
						</div>
					</div>
				</div>
			</div>

app/views/pages/disclaimer.html.erb
		<!-- Main -->
			<div class="wrapper style2">
				<div class="title">|DISCLAIMER & RULES|</div>
				<div id="main" class="container">
							
					<!-- Content -->
						<div id="content">
							<article class="box post">
								<header class="style1">
									<h2>Our Leave No Trace Methodology and our Safety Disclaimer.	</h2>
									<p>We <strong> Guarantee </strong> safe travel, return, and no consequences to the future of the human race.</p>
								</header>
								<a href="#" class="image featured">
									<img src="/assets/aboutpic.jpg" alt="" />
								</a>
							
<h2>RULES OF THE ROAD</h2>
<ol "type=1"><strong>
	<li> There will be no presence of the future in the past that could blow our cover.</li>
	<li> You will be issued a counterfiet vintage passport thourgh our online store that will verify your identy you are required to carry this with you.</li>
	<li>You are required to stay with the group under supervision as we cannot guarantee a rescue if you are left behind and the worm hole closes up.</li>
	<li>You are prohibited from interacting with humanity from the past.</li>
	<li>You will be issued a uniform that is custom selected to disguise you in the era of each trip. You will be required to wear your uniform.</li>

	<li>Never confess to the truth, we under no circumstances effect the future of humanity. Our investiations are to benefit the future of our current state of humanity. </li>
</strong>
</ol>




<h1>Disclaimer and Copyright</h1>






<p>All materials on this site are protected by copyright and intellectual property laws. </p>

<p>Visitors who use this website and rely on any information do so at their own risk. </p>

<p>By sharing any contribution (including any text, photographs, graphics, video or audio) with us you agree to grant us, free of charge, permission to use the material in any way we want (including modifying or deleting it). In order that we can use your contribution, you confirm that your contribution is your own original work, is not defamatory and does not infringe any laws and that you have the right to give us permission to use it for the purposes specified above. </p>

<p>The operators of wwwow.eu are not responsible for the contents or reliability of any other websites linked to this website and do not necessarily endorse the views expressed within them. 
<p>Users must not use this website in any way which is unlawful, illegal, fraudulent or harmful, or in connection with any unlawful, illegal, fraudulent or harmful purpose or activity. The majority of content posted in this forum is created by members of the public. The views expressed are theirs and unless specifically stated are not those of the operators of wwwow.eu .We accept no responsibility for any loss or harm incurred.</p>

<p>blackmagic is a website with an open and interactive division, it is therefore not possible to monitor changes in this area. We reserve the right to remove materials such as comments, photos or videos concerning pornographic, abusive or defamatory topics. We also reserve the right to remove documents concerning quackery, detected harmful interventions, statements contrary to public policy and violations of ethic norms. We request the users to inform us as soon as they detect such contents listed above or content they perceive as inappropriate or incorrect. </p>

<p>We are not responsible for the contents or reliability of any other websites to which we provide a link and do not necessarily endorse the views expressed within them. </p>

<p>You may link to our home page, provided you do so in a way that is fair and legal and does not damage our reputation or take advantage of it, but you must not establish a link in such a way as to suggest any form of association, approval or endorsement on our part where none exists. 
You must not establish a link from any website that is not owned by you. 
Our site must not be framed on any other site, nor may you create a link to any part of our site other than the home page without our express permission. We reserve the right to withdraw linking permission without notice. </p>


<h1>Privacy Policy</h1>

<p>Personal data entered on our site (e.g. name, email, address or exchange program) are provided voluntarily. The use or processing of these data through third parties is strictly prohibited. The operators of wwwow.eu do not accept any responsibility whatsoever for illegal and abusive use of these data.</p>
							</article>
							<div class="row 150%">
								<div class="4u">
								</div>
								<div class="4u">
									<section class="box">
										<header>
											<h2>Book Your Reservation Today</h2>
										</header>
										<a href="#" class="image featured"><img src="/assets/pic07.jpg" alt="" /></a>
										<a href="#" class="button style1">More</a>
									</section>
								</div>
								<div class="4u">
									
								</div>
							</div>
						</div>

				</div>
			</div>

app/views/pages/documents.html.erb
<h1>Pages#documents</h1>
<p>Find me in app/views/pages/documents.html.erb</p>

app/views/pages/itinerary.html.erb
		<!-- Main -->
			<div class="wrapper style2">
				<div class="title">|Itinerary|</div>
				<div id="main" class="container">
					<div class="row 150%">
						<div class="8u">
						
							<!-- Content -->
								<div id="content">
									<article class="box post">
										<header class="style1">
											<h2>Get your travel Itinerary, and review the details of your journey.</h2>
											<p>"If art is to nourish the roots of our culture, society must set the artist free to follow his vision wherever it takes him." <br>~John F. Kennedy</p>
										</header>
										<a href="#" class="image featured">
											<img src="/assets/brochure.jpg" alt="" />
										</a>
										<p>When traveling back in time through a wormhole, it is very important that we adhere to a strict schedule, so as to ensure that we arrive at our event, and we can exit before the worm hole closes up.</p>
										<p>Each Itinerary is designed custom to the event we are traveling too. This month we are traveling back to the Assassination of John F. Kennedy.  Kennedy was assinated on November 22, 1963 in Dallas Texas.</p>
										<p>We here at Black Magic Time Travel Sollutions have consulted American History professors at Harvard, Yale, and George Washington to develop the best possible time hop itinerary for this incredibly historical event.</p>
										<p>Your Itinerary will be sent to you in the mail inside one of the envelops below, as well as your counterfiet passport to legitimize your story. You need to head over to our store and get fit for an Official Black Magic Team Uniform.</p>
										<img src="/assets/folder.jpg" alt="" width="100%" height = "500"/>
										<p>Please keep all travel documents including your ticket, your passport, and your itinerary inside our folder, with you at all times along the journey. This is to insure your safety.</p>
									</article>

								</div>
						
						</div>
						<div class="4u">
							
							<!-- Sidebar -->
								<div id="sidebar">
									<section class="box">
										<header>
											<h2>Time-Line of Imporating Events</h2>
										</header>
										<p>No other story in the history of the United States of America is shrouded in as much conspiracy and questions than the John F. Kennedy Assasination.</p>
										<a href="#" class="button style1">Learn More</a>
									</section>
									<section class="box">
										<header>
											<h2>November 22, 1963</h2>
										</header>
										<ul class="style2">
											<li>
												<article class="box post-excerpt">
													<a href="#" class="image left"><img src="/assets/crowd.jpg" alt="" /></a>
													<h3>11:38 AM </h3>
													<p>Air Force One had landed at Love Field Airport in Dallas Texas. At 11:38 am President Kennedy was seen greeting the crowd at the airport.</p>
												</article>
											</li>
											<li>
												<article class="box post-excerpt">
													<a href="#" class="image left"><img src="/assets/car.jpg" alt="" /></a>
													<h3>12:21 PM</h3>
													<p>At 12:21 the President's motorcade turned down Main Street with his wife Jackie at his side. They were photographed waving to crowded streets.</p>
												</article>
											</li>
											<li>
												<article class="box post-excerpt">
													<a href="#" class="image left"><img src="/assets/shot.jpg" alt="" /></a>
													<h3><a href="#">12:30 PM</a></h3>
													<p>Shots ring out and the President is shot and killed in broad daylight. Lee Harvy Oswald is arrested 10 minutes later.</p>
												</article>
											</li>
																						<li>
												<article class="box post-excerpt">
													<a href="#" class="image left"><img src="/assets/oldlee.jpg" alt="" /></a>
													<h3>2:20 PM</h3>
													<p>Lee Harvey Oswald was interviewd for the first time in regards to the shooting of the President.</p>
												</article>
											</li>
											<li>
												<h2>November 24th</h2>
												<article class="box post-excerpt">
													<a href="#" class="image left"><img src="/assets/shotson.jpg" alt="" /></a>

													<h3><a href="#">11:21 AM </a></h3>
													<p>Lee Harvey Oswald was shot and killed leaving the Dallas Jail where he was being held.</p>
												</article>
											</li>
										</ul>
										<a href="#" class="button style1">Archives</a>
									</section>
								</div>
							
						</div>
					</div>
				</div>
			</div>

app/views/pages/store.html.erb
	<!-- Main -->
			<div class="wrapper style2">
				<div class="title">|ONLINE STORE|</div>
				<div id="main" class="container">
					<div class="row 150%">
						<div class="8u">
						
							<!-- Content -->
								<div id="content">
									<article class="box post">
										<header class="style1">
											<h2>Get your official Black Magic Gear needed for your trip into the past.</h2>
											<p>Don't Forget to be in uniform on our departure date.</p>
										</header>
										<a href="#" class="image featured">
											<img src="/assets/travelkit.jpg" alt="" />
										</a>
										<br>
										<p>It is very important that we dress to fit in to every event we travel to. Our very talented stylist put together an awesome hipster look for our trip back to 1963.</p>
										<p>Make sure to follow up with our tailor to get custom fit for your team uniform.</p><br><br>
										<img src="/assets/branding.jpg" alt="" width="100%" height= "500"/>
										<br><br>
										<p>Don't miss thia opportunity to grab our complimentary stationary set as a part of our John F. Kennedy promotional giveaway.</p> 
									</article>
									<div class="row 150%">
										<div class="6u">
											
										</div>
										<div class="6u">
											
										</div>
									</div>
								</div>
						
						</div>
						<div class="4u">
							
							<!-- Sidebar -->
								<div id="sidebar">
									<section class="box">
										<header>
											<h2>More About Our Stylists</h2>
										</header>
										<p>Black Magic Time Travel Sollutions has employed top stylists who design wonderful team uniforms to keep your identity a secret as you travel back in time.</p>
										<a href="#" class="button style1">Learn More</a>
									</section>
						
								</div>
							
						</div>
					</div>
				</div>
			</div>

app/views/purchases/edit.html.erb
<h1>Editing Purchase</h1>

<%= render 'form' %>

<%= link_to 'Show', @purchase %> |
<%= link_to 'Back', purchases_path %>

app/views/purchases/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', purchases_path %>

app/views/purchases/show.html.erb
<p id="notice"><%= notice %></p>

    <!-- Ticket-->
      <div id="intro-wrapper" class="wrapper style1">
        <div class="title">|Passenger Ticket|</div>
       
<table class="defualt">
  <tr>
    <td>
      <img src="/assets/logo.jpg" width="100" height="100" alt="" />
    </td>
  </tr>
  <tr>
    <td> 
        <strong>First Name: </strong>
        <%= @purchase.fname %>
    </td>
    <td>
        <strong>Last Name:</strong>
             <%= @purchase.lname %>
    </td>

  </tr>
  <tr>
    <td>
      <strong>Destination: </strong>
      Dallas Texas, 1963
    </td>
    <td>
        <strong>Event:</strong>
        The Assasination of JFK
    </td> 
    <td>
      <strong>Departure: </strong>
      May 7th, 2015. CCRI Warwick, Rhode Island
    </td>
  </tr>
  <tr>
    <td>
        <strong>Gate Number: 4078</strong>
    </td>
        <td>
        <strong>Seat Number: </strong>
        420-A
    </td>
        <td>
        <strong>Return: </strong>
      May 7th, 2015. CCRI Warick, Rhoe Island
    </td>
  </tr>
  <tr>
    <td>
    </td>
    <td>
          <td>
            <strong>Ticket#:</strong>
          <%=@purchase.id %>
      <img src="/assets/barcode.jpg" width="200" height="100" alt="" />
    </td>
</tr>
</table>
<p>
  <strong>Requests:</strong>
  <%= @purchase.requests %>
</p>
          <ul class="actions">
            <li><a href="#" class="button style3 big">Thank You For Flying Black Magic</a></li>
          </ul>
        </section>
      </div>
    

<%= link_to 'Edit', edit_purchase_path(@purchase) %> |
<%= link_to 'Back', purchases_path %>